modLoader="javafml" #mandatory
license="MIT"
loaderVersion="[39,)" #mandatory

[[mods]] #mandatory
modId="nbttool" #mandatory
version="${file.jarVersion}" #mandatory
displayName="NBT Tool" #mandatory
logoFile="nbttool-logo.png"
credits="" #optional
authors="haoict"
description='''
This mod displays the item NBT tag on their tooltip when advanced tooltips (F3+H) are enabled.
'''
